### ISSUE TITLE
There is a problem processing outgoing mail queue — an admin should check System Status and Recommendations

### ISSUE THREAD

**Issue by pnkr** [freescout-help-desk/freescout#4216]
PHP version: 8.2.23
FreeScout version: 1.8.152
Database: Mysql (10.6.18-MariaDB-0ubuntu0.22.04.1) 
Are you using CloudFlare: Yes
Are you using non-official modules:  No

System status (PHP Extensions, Functions, Permissions) are all OK.
but queue: work reports this: queue:work  Last run: ? Last successful run: ? Try to clear cache to force command to start.

I clear the cache but the same problem remains

The queue now has more than 100 jobs to be done but its just stuck.

I rebooted the server but the same issue persists. 

I run php artisan freescout clear-cache but the queue does not start again

On my log files i see a list of issues like this

```
 file_put_contents(/site-url-path/storage/framework/cache/data/71/e7/71e745d13645beba997b5011324db8ee58db0e30): Failed to open stream: Permission denied {"exception":"[object] (ErrorException(code: 0): file_put_contents(/site-url-path/storage/framework/cache/data/71/e7/71e745d13645beba997b5011324db8ee58db0e30): Failed to open stream: Permission denied at /site-url-path/overrides/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122) 

[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /site-url-path/overrides/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents()
#2 /site-url-path/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(64): Illuminate\\Filesystem\\Filesystem->put()
#3 /site-url-path/overrides/laravel/framework/src/Illuminate/Cache/Repository.php(195): Illuminate\\Cache\\FileStore->put()
#4 /site-url-path/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(304): Illuminate\\Cache\\Repository->put()
#5 /site-url-path/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Cache\\CacheManager->__call()
#6 /site-url-path/app/Console/Kernel.php(179): Illuminate\\Support\\Facades\\Facade::__callStatic()
#7 /site-url-path/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(106): App\\Console\\Kernel->schedule()
#8 /site-url-path/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(89): Illuminate\\Foundation\\Console\\Kernel->defineConsoleSchedule()
#9 [internal function]: Illuminate\\Foundation\\Console\\Kernel->Illuminate\\Foundation\\Console\\{closure}()
#10 /site-url-path/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(831): call_user_func()
#11 /site-url-path/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(780): Illuminate\\Foundation\\Application->fireAppCallbacks()
#12 /site-url-path/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#13 /site-url-path/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(213): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#14 /site-url-path/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(296): Illuminate\\Foundation\\Application->bootstrapWith()
#15 /site-url-path/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(119): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#16 /site-url-path/artisan(60): Illuminate\\Foundation\\Console\\Kernel->handle()
#17 {main}
"}
```
                    

But the permissions on my system page is all OK.

**Comment by pnkr** [comment]
in terminal i hit php artisan queue:work and the prosses starts but after a while it gets killed automaticaly.

Checking the logs I see a lot of tries like this
Send error. Connection could not be established with host 'mailhost' [Connection timed out #110]. Message-ID:xxxxxxx

**Comment by freescout-help** [comment]
https://github.com/freescout-help-desk/freescout/wiki/Installation-Guide#11-troubleshooting

https://github.com/freescout-help-desk/freescout/wiki/Sending-Issues

**Comment by SecteurA** [comment]
How did you solve this, i have same issue and total of 100 emails :(

**Comment by pnkr** [comment]
The issue was that there were 3 emails being send to an incorrect email address. I deleted from the database those two and did the same thing running php artisan queue:work
