### ISSUE TITLE
cannot create conversation via API

### ISSUE THREAD

**Issue by mokkin** [freescout-help-desk/freescout#4285]
I'm trying to create a conversation via n8n and API. Unfortunately I'm getting a 500 error without further specification.

```
{
  "errorMessage": "The service was not able to process your request [item 0]",
  "errorDescription": "Server Error",
  "errorDetails": {
    "rawErrorMessage": [
      "500 - \"{\\n    \\\"message\\\": \\\"Server Error\\\"\\n}\""
    ],
    "httpCode": "500"
  },
  "n8nDetails": {
    "nodeName": "create conversation",
    "nodeType": "n8n-nodes-base.httpRequest",
    "nodeVersion": 4.2,
    "itemIndex": 0,
    "time": "13.10.2024, 10:29:04",
    "n8nVersion": "1.62.5 (Self Hosted)",
    "binaryDataMode": "default",
    "stackTrace": [
      "NodeApiError: The service was not able to process your request",
      "    at Object.execute (/usr/local/lib/node_modules/n8n/node_modules/n8n-nodes-base/dist/nodes/HttpRequest/V3/HttpRequestV3.node.js:1649:33)",
      "    at processTicksAndRejections (node:internal/process/task_queues:95:5)",
      "    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:19)",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:711:51",
      "    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1141:20"
    ]
  }
}
```
The request sent in the body was:

```
{
    "type": "email",
    "mailboxId": 7,
    "subject": "Mahlzeit",
    "customer": {
        "email": "support@example.de"
    },
    "threads": [
        {
            "text": "This is the message from a user",
            "type": "message",
            "user": 1
        }
    ],
    "status": "closed"
}

```

Please note that the email is successfully sent to the recipient, but no conversation is created.

PHP version: 8.2.24
FreeScout version: 1.8.154
Database: MySQL
Are you using CloudFlare: No
Are you using non-official modules: Yes
API version: 1.0.81

**Comment by ilyakonovalenko** [comment]
Please check FreeScout errors log.

**Comment by mokkin** [comment]
Thanks for the hint. It's seems it's because of our custom module:

```
 Attempt to read property "id" on null {"exception":"[object] (ErrorException(code: 0): Attempt to read property \"id\" on null at /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/Modules/AmeiseModule/Providers/AmeiseModuleServiceProvider.php:75)
[stacktrace]
#0 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/Modules/AmeiseModule/Providers/AmeiseModuleServiceProvider.php(75): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Attempt to read...', '/var/www/vhosts...', 75)
#1 [internal function]: Modules\\AmeiseModule\\Providers\\AmeiseModuleServiceProvider->Modules\\AmeiseModule\\Providers\\{closure}(Object(App\\Conversation))
#2 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/overrides/tormjens/eventy/src/Action.php(26): call_user_func_array(Object(Closure), Array)
#3 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/tormjens/eventy/src/Events.php(139): TorMorten\\Eventy\\Action->fire('conversation.cr...', Array)
#4 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): TorMorten\\Eventy\\Events->action('conversation.cr...', Object(App\\Conversation), Object(App\\Thread))
#5 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/Modules/ApiWebhooks/Http/Controllers/ApiController.php(1147): Illuminate\\Support\\Facades\\Facade::__callStatic('action', Array)
#6 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/Modules/ApiWebhooks/Http/Controllers/ApiController.php(775): Modules\\ApiWebhooks\\Http\\Controllers\\ApiController->createThread(Object(Illuminate\\Http\\Request), 58425, true)
#7 [internal function]: Modules\\ApiWebhooks\\Http\\Controllers\\ApiController->createConversation(Object(Illuminate\\Http\\Request))
#8 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/overrides/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#9 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('createConversat...', Array)
#10 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Routing/Route.php(211): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Modules\\ApiWebhooks\\Http\\Controllers\\ApiController), 'createConversat...')
#11 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#12 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/overrides/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#13 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#14 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/Modules/ApiWebhooks/Http/Middleware/ApiAuth.php(32): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Modules\\ApiWebhooks\\Http\\Middleware\\ApiAuth->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/overrides/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#22 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/overrides/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#23 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/overrides/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#24 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/overrides/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#25 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#26 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/app/Http/Middleware/TerminateHandler.php(12): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\TerminateHandler->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/app/Http/Middleware/ResponseHeaders.php(11): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): App\\Http\\Middleware\\ResponseHeaders->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#50 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#51 /var/www/vhosts/hosting123456.a2fee.netcup.net/httpdocs/support.example.de/public/index.php(82): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#52 {main}
"}
                    

```

If I dectivate it the conversation is getting successfully created.
